-- Create attendance table for employee work shifts (clock-in/out, breaks)
CREATE TABLE public.attendance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  date date NOT NULL,
  clock_in timestamptz NOT NULL,
  clock_out timestamptz,
  clock_in_location jsonb,
  clock_out_location jsonb,
  breaks jsonb DEFAULT '[]'::jsonb,
  break_minutes integer DEFAULT 0,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'submitted', 'approved', 'locked')),
  note text,
  autogenerated boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),

  -- One attendance per employee per day
  UNIQUE(employee_id, date)
);

-- Indexes for common queries
CREATE INDEX idx_attendance_employee_id ON public.attendance(employee_id);
CREATE INDEX idx_attendance_company_id ON public.attendance(company_id);
CREATE INDEX idx_attendance_date ON public.attendance(date);
CREATE INDEX idx_attendance_status ON public.attendance(status);
CREATE INDEX idx_attendance_employee_date ON public.attendance(employee_id, date);

-- Enable RLS
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

-- Employees can view their own attendance
CREATE POLICY "Employees can view own attendance"
  ON public.attendance FOR SELECT
  USING (
    employee_id IN (
      SELECT id FROM public.employees WHERE user_id = auth.uid()
    )
  );

-- Employees can insert their own attendance
CREATE POLICY "Employees can insert own attendance"
  ON public.attendance FOR INSERT
  WITH CHECK (
    employee_id IN (
      SELECT id FROM public.employees WHERE user_id = auth.uid()
    )
  );

-- Employees can update their own open attendance
CREATE POLICY "Employees can update own attendance"
  ON public.attendance FOR UPDATE
  USING (
    employee_id IN (
      SELECT id FROM public.employees WHERE user_id = auth.uid()
    )
  );

-- Managers can view all company attendance
CREATE POLICY "Managers can view company attendance"
  ON public.attendance FOR SELECT
  USING (
    has_role(auth.uid(), 'manager'::user_role) AND
    company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid())
  );

-- Managers can update company attendance (approve/lock)
CREATE POLICY "Managers can update company attendance"
  ON public.attendance FOR UPDATE
  USING (
    has_role(auth.uid(), 'manager'::user_role) AND
    company_id = (SELECT company_id FROM public.profiles WHERE id = auth.uid())
  );

-- Updated_at trigger
CREATE OR REPLACE FUNCTION public.update_attendance_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER attendance_updated_at
  BEFORE UPDATE ON public.attendance
  FOR EACH ROW
  EXECUTE FUNCTION public.update_attendance_updated_at();
